# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iE9cioG-oxMWes67A32NhSVcxek6CtYt
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

yol = '/content/drive/MyDrive/archive/'

df_dataset = pd.read_csv(yol + 'dataset.csv')
df_aciklama = pd.read_csv(yol + 'symptom_Description.csv')
df_onlem = pd.read_csv(yol + 'symptom_precaution.csv')
df_siddet = pd.read_csv(yol + 'Symptom-severity.csv')

print(f"dataset.csv → {df_dataset.shape[0]} satır, {df_dataset.shape[1]} sütun")

print(f"Toplam hastalık sayısı: {df_dataset['Disease'].nunique()}")
print("\nHastalık listesi:")
for i, h in enumerate(sorted(df_dataset['Disease'].unique()), 1):
    print(f"  {i}. {h}")

print("SEMPTOMLAR")
semptom_sutunlari = [f'Symptom_{i}' for i in range(1, 18)]
tum_semptomlar = pd.Series(df_dataset[semptom_sutunlari].values.ravel())
tum_semptomlar = tum_semptomlar.dropna().str.strip().unique()

print(f"Toplam benzersiz semptom sayısı: {len(tum_semptomlar)}")

print("NaN  DEĞERLER")
print(df_dataset.isnull().sum())

!pip install googletrans==4.0.0-rc1 -q

from googletrans import Translator
import time

translator = Translator()

hastalilar_ing = sorted(df_dataset['Disease'].unique())
hastalik_cevirisi = {}

for hastalik in hastalilar_ing:
    try:
        ceviri = translator.translate(hastalik, src='en', dest='tr')
        hastalik_cevirisi[hastalik] = ceviri.text
        print(f"{hastalik} → {ceviri.text}")
        time.sleep(0.3)
    except:
        hastalik_cevirisi[hastalik] = hastalik
        print(f"{hastalik} → ÇEVİRİ HATASI")

print("\ntamamlandı")

hastalik_cevirisi = {
    '(vertigo) Paroymsal  Positional Vertigo': 'Paroksismal Pozisyonel Vertigo',
    'AIDS': 'AIDS',
    'Acne': 'Akne',
    'Alcoholic hepatitis': 'Alkolik Hepatit',
    'Allergy': 'Alerji',
    'Arthritis': 'Artrit',
    'Bronchial Asthma': 'Bronşiyal Astım',
    'Cervical spondylosis': 'Servikal Spondiloz',
    'Chicken pox': 'Suçiçeği',
    'Chronic cholestasis': 'Kronik Kolestaz',
    'Common Cold': 'Soğuk Algınlığı',
    'Dengue': 'Dang Humması',
    'Diabetes ': 'Diyabet',
    'Dimorphic hemmorhoids(piles)': 'Hemoroid (Basur)',
    'Drug Reaction': 'İlaç Reaksiyonu',
    'Fungal infection': 'Mantar Enfeksiyonu',
    'GERD': 'Gastroözofajeal Reflü',
    'Gastroenteritis': 'Gastroenterit',
    'Heart attack': 'Kalp Krizi',
    'Hepatitis B': 'Hepatit B',
    'Hepatitis C': 'Hepatit C',
    'Hepatitis D': 'Hepatit D',
    'Hepatitis E': 'Hepatit E',
    'Hypertension ': 'Hipertansiyon',
    'Hyperthyroidism': 'Hipertiroidizm',
    'Hypoglycemia': 'Hipoglisemi',
    'Hypothyroidism': 'Hipotiroidizm',
    'Impetigo': 'İmpetigo',
    'Jaundice': 'Sarılık',
    'Malaria': 'Sıtma',
    'Migraine': 'Migren',
    'Osteoarthristis': 'Osteoartrit',
    'Paralysis (brain hemorrhage)': 'Felç (Beyin Kanaması)',
    'Peptic ulcer diseae': 'Peptik Ülser',
    'Pneumonia': 'Zatürre',
    'Psoriasis': 'Sedef Hastalığı',
    'Tuberculosis': 'Tüberküloz',
    'Typhoid': 'Tifo',
    'Urinary tract infection': 'İdrar Yolu Enfeksiyonu',
    'Varicose veins': 'Varisli Damarlar',
    'hepatitis A': 'Hepatit A'
}

for ing, tr in hastalik_cevirisi.items():
    print(f"{ing} → {tr}")

import numpy as np

semptom_kolonlari = [f'Symptom_{i}' for i in range(1, 18)]
tum_semptomlar = set()

for kolon in semptom_kolonlari:
    degerler = df_dataset[kolon].dropna().unique()
    for deger in degerler:
        temiz = deger.strip()
        if temiz:
            tum_semptomlar.add(temiz)

tum_semptomlar = sorted(tum_semptomlar)
print(f"Toplam {len(tum_semptomlar)} benzersiz semptom bulundu.")
print("=" * 50)

# Semptomları çevir
print("Semptomlar çevriliyor...")
semptom_cevirisi = {}

for i, semptom in enumerate(tum_semptomlar):
    try:
        ceviri = translator.translate(semptom, src='en', dest='tr')
        semptom_cevirisi[semptom] = ceviri.text
        print(f"{semptom} → {ceviri.text}")
        time.sleep(0.3)
    except:
        semptom_cevirisi[semptom] = semptom
        print(f"{semptom} → ÇEVİRİ HATASI")

print(f"\n✅ Toplam {len(semptom_cevirisi)} semptom çevrildi!")

import numpy as np

semptom_kolonlari = [f'Symptom_{i}' for i in range(1, 18)]
tum_semptomlar = set()

for kolon in semptom_kolonlari:
    degerler = df_dataset[kolon].dropna().unique()
    for deger in degerler:
        temiz = deger.strip()
        if temiz:
            tum_semptomlar.add(temiz)

tum_semptomlar = sorted(tum_semptomlar)
print(f"Toplam {len(tum_semptomlar)} benzersiz semptom bulundu.")


semptom_cevirisi = {}

for i, semptom in enumerate(tum_semptomlar):
    try:
        ceviri = translator.translate(semptom, src='en', dest='tr')
        semptom_cevirisi[semptom] = ceviri.text
        print(f"{semptom} → {ceviri.text}")
        time.sleep(0.3)
    except:
        semptom_cevirisi[semptom] = semptom
        print(f"{semptom} → ÇEVİRİ HATASI")

print(f"\nToplam {len(semptom_cevirisi)} semptom çevrildi!")

semptom_cevirisi = {
    'abdominal_pain': 'karın ağrısı',
    'abnormal_menstruation': 'anormal adet düzensizliği',
    'acidity': 'mide asidi',
    'acute_liver_failure': 'akut karaciğer yetmezliği',
    'altered_sensorium': 'bilinç değişikliği',
    'anxiety': 'anksiyete',
    'back_pain': 'sırt ağrısı',
    'belly_pain': 'göbek ağrısı',
    'blackheads': 'siyah nokta',
    'bladder_discomfort': 'mesane rahatsızlığı',
    'blister': 'su kabarcığı',
    'blood_in_sputum': 'balgamda kan',
    'bloody_stool': 'kanlı dışkı',
    'blurred_and_distorted_vision': 'bulanık ve bozuk görme',
    'breathlessness': 'nefes darlığı',
    'brittle_nails': 'kırılgan tırnaklar',
    'bruising': 'morarma',
    'burning_micturition': 'yanma ile idrara çıkma',
    'chest_pain': 'göğüs ağrısı',
    'chills': 'üşüme',
    'cold_hands_and_feets': 'soğuk eller ve ayaklar',
    'coma': 'koma',
    'congestion': 'burun tıkanıklığı',
    'constipation': 'kabızlık',
    'continuous_feel_of_urine': 'sürekli idrara sıkışma hissi',
    'continuous_sneezing': 'sürekli hapşırma',
    'cough': 'öksürük',
    'cramps': 'kramp',
    'dark_urine': 'koyu renkli idrar',
    'dehydration': 'dehidrasyon',
    'depression': 'depresyon',
    'diarrhoea': 'ishal',
    'dischromic _patches': 'renk değişimi lekeleri',
    'distention_of_abdomen': 'karın şişkinliği',
    'dizziness': 'baş dönmesi',
    'drying_and_tingling_lips': 'dudak kuruması ve karıncalanma',
    'enlarged_thyroid': 'büyümüş tiroid',
    'excessive_hunger': 'aşırı açlık',
    'extra_marital_contacts': 'cinsel temas öyküsü',
    'family_history': 'aile hastalık geçmişi',
    'fast_heart_rate': 'hızlı kalp atışı',
    'fatigue': 'yorgunluk',
    'fluid_overload': 'sıvı aşırı yüklenmesi',
    'foul_smell_of urine': 'kötü kokulu idrar',
    'headache': 'baş ağrısı',
    'high_fever': 'yüksek ateş',
    'hip_joint_pain': 'kalça eklem ağrısı',
    'history_of_alcohol_consumption': 'alkol kullanım geçmişi',
    'increased_appetite': 'artan iştah',
    'indigestion': 'hazımsızlık',
    'inflammatory_nails': 'iltihaplanmış tırnaklar',
    'internal_itching': 'iç kaşıntı',
    'irregular_sugar_level': 'düzensiz kan şekeri',
    'irritability': 'sinirlilik',
    'irritation_in_anus': 'anüs tahrişi',
    'itching': 'kaşıntı',
    'joint_pain': 'eklem ağrısı',
    'knee_pain': 'diz ağrısı',
    'lack_of_concentration': 'konsantrasyon güçlüğü',
    'lethargy': 'halsizlik',
    'loss_of_appetite': 'iştah kaybı',
    'loss_of_balance': 'denge kaybı',
    'loss_of_smell': 'koku kaybı',
    'malaise': 'genel vücut yorgunluğu',
    'mild_fever': 'hafif ateş',
    'mood_swings': 'ruh hali dalgalanmaları',
    'movement_stiffness': 'hareket tutukluğu',
    'mucoid_sputum': 'mukuslu balgam',
    'muscle_pain': 'kas ağrısı',
    'muscle_wasting': 'kas erimesi',
    'muscle_weakness': 'kas güçsüzlüğü',
    'nausea': 'bulantı',
    'neck_pain': 'boyun ağrısı',
    'nodal_skin_eruptions': 'nodüler cilt döküntüsü',
    'obesity': 'obezite',
    'pain_behind_the_eyes': 'göz arkası ağrısı',
    'pain_during_bowel_movements': 'dışkılama sırasında ağrı',
    'pain_in_anal_region': 'anüs bölgesinde ağrı',
    'painful_walking': 'ağrılı yürüyüş',
    'palpitations': 'çarpıntı',
    'passage_of_gases': 'gaz çıkarma',
    'patches_in_throat': 'boğazda leke',
    'phlegm': 'balgam',
    'polyuria': 'sık idrara çıkma',
    'prominent_veins_on_calf': 'baldırda belirgin damarlar',
    'puffy_face_and_eyes': 'şişmiş yüz ve gözler',
    'pus_filled_pimples': 'irin dolu sivilce',
    'receiving_blood_transfusion': 'kan transfüzyonu alma',
    'receiving_unsterile_injections': 'steril olmayan enjeksiyon',
    'red_sore_around_nose': 'burun çevresinde kızarıklık',
    'red_spots_over_body': 'vücutta kırmızı lekeler',
    'redness_of_eyes': 'göz kızarıklığı',
    'restlessness': 'huzursuzluk',
    'runny_nose': 'burun akıntısı',
    'rusty_sputum': 'paslı renkli balgam',
    'scurring': 'kabuk oluşumu',
    'shivering': 'titreme',
    'silver_like_dusting': 'gümüş rengi pullanma',
    'sinus_pressure': 'sinüs basıncı',
    'skin_peeling': 'cilt soyulması',
    'skin_rash': 'cilt döküntüsü',
    'slurred_speech': 'peltek konuşma',
    'small_dents_in_nails': 'tırnaklarda çukurlaşma',
    'spinning_movements': 'dönme hissi',
    'spotting_ urination': 'lekeli idrara çıkma',
    'stiff_neck': 'boyun tutulması',
    'stomach_bleeding': 'mide kanaması',
    'stomach_pain': 'mide ağrısı',
    'sunken_eyes': 'çökmüş gözler',
    'sweating': 'terleme',
    'swelled_lymph_nodes': 'şişmiş lenf düğümleri',
    'swelling_joints': 'eklem şişmesi',
    'swelling_of_stomach': 'mide şişmesi',
    'swollen_blood_vessels': 'şişmiş kan damarları',
    'swollen_extremeties': 'şişmiş ekstremiteler',
    'swollen_legs': 'şişmiş bacaklar',
    'throat_irritation': 'boğaz tahrişi',
    'toxic_look_(typhos)': 'toksik görünüm',
    'ulcers_on_tongue': 'dil ülseri',
    'unsteadiness': 'dengesizlik',
    'visual_disturbances': 'görsel bozukluklar',
    'vomiting': 'kusma',
    'watering_from_eyes': 'gözden su akması',
    'weakness_in_limbs': 'uzuvlarda güçsüzlük',
    'weakness_of_one_body_side': 'vücudun bir tarafında güçsüzlük',
    'weight_gain': 'kilo alımı',
    'weight_loss': 'kilo kaybı',
    'yellow_crust_ooze': 'sarı kabuk akıntısı',
    'yellow_urine': 'sarı idrar',
    'yellowing_of_eyes': 'gözlerin sararması',
    'yellowish_skin': 'sarı cilt',
}

import pandas as pd

df_turkce = df_dataset.copy()

df_turkce['Disease'] = df_turkce['Disease'].map(lambda x: hastalik_cevirisi.get(x.strip(), x.strip()))

semptom_kolonlari = [f'Symptom_{i}' for i in range(1, 18)]

for kolon in semptom_kolonlari:
    df_turkce[kolon] = df_turkce[kolon].map(
        lambda x: semptom_cevirisi.get(x.strip(), x.strip()) if pd.notna(x) else x
    )

print(f"Satır sayısı: {len(df_turkce)}")
print(df_turkce[['Disease', 'Symptom_1', 'Symptom_2', 'Symptom_3']].head(3))

print("\nHastalık listesi (Türkçe):")
print(sorted(df_turkce['Disease'].unique()))

df_turkce['Disease'] = df_turkce['Disease'].replace({
    'Diabetes': 'Diyabet',
    'Hypertension': 'Hipertansiyon'
})

print("Hastalık listesi :")
print(sorted(df_turkce['Disease'].unique()))

df_turkce.to_csv('/content/drive/MyDrive/archive/dataset_turkce.csv', index=False)
print("\nkaydedildi")

df_desc = pd.read_csv('/content/drive/MyDrive/archive/symptom_Description.csv')
df_precaution = pd.read_csv('/content/drive/MyDrive/archive/symptom_precaution.csv')
df_severity = pd.read_csv('/content/drive/MyDrive/archive/Symptom-severity.csv')

df_desc_tr = df_desc.copy()
df_desc_tr['Disease'] = df_desc_tr['Disease'].map(
    lambda x: hastalik_cevirisi.get(x.strip(), x.strip())
).replace({'Diabetes': 'Diyabet', 'Hypertension': 'Hipertansiyon'})

aciklamalar_tr = []
for metin in df_desc_tr['Description']:
    try:
        ceviri = translator.translate(metin, src='en', dest='tr')
        aciklamalar_tr.append(ceviri.text)
        time.sleep(0.3)
    except:
        aciklamalar_tr.append(metin)
df_desc_tr['Description'] = aciklamalar_tr

df_desc_tr.to_csv('/content/drive/MyDrive/archive/symptom_Description_turkce.csv', index=False)
print(" symptom_Description_turkce.csv kaydedildi")
print(df_desc_tr.head(3))

# === symptom_precaution.csv ===
df_prec_tr = df_precaution.copy()

df_prec_tr['Disease'] = df_prec_tr['Disease'].map(
    lambda x: hastalik_cevirisi.get(x.strip(), x.strip())
).replace({'Diabetes': 'Diyabet', 'Hypertension': 'Hipertansiyon'})

print("\nÖnlemler çevriliyor...")
for kolon in ['Precaution_1', 'Precaution_2', 'Precaution_3', 'Precaution_4']:
    cevrilen = []
    for metin in df_prec_tr[kolon]:
        if pd.notna(metin):
            try:
                ceviri = translator.translate(str(metin), src='en', dest='tr')
                cevrilen.append(ceviri.text)
                time.sleep(0.3)
            except:
                cevrilen.append(metin)
        else:
            cevrilen.append(metin)
    df_prec_tr[kolon] = cevrilen

df_prec_tr.to_csv('/content/drive/MyDrive/archive/symptom_precaution_turkce.csv', index=False)
print("symptom_precaution_turkce.csv kaydedildi!")
print(df_prec_tr.head(3))

df_sev_tr = df_severity.copy()

df_sev_tr['Symptom'] = df_sev_tr['Symptom'].map(
    lambda x: semptom_cevirisi.get(x.strip(), x.strip())
)

df_sev_tr.to_csv('/content/drive/MyDrive/archive/Symptom_severity_turkce.csv', index=False)
print("\nSymptom_severity_turkce.csv kaydedildi!")
print(df_sev_tr.head(5))

from sklearn.preprocessing import LabelEncoder
import numpy as np

df_ml = df_turkce.copy()

semptom_kolonlari = [f'Symptom_{i}' for i in range(1, 18)]
df_ml[semptom_kolonlari] = df_ml[semptom_kolonlari].fillna('')

print(f"NaN sayısı: {df_ml.isnull().sum().sum()}")

tum_semptomlar_listesi = list(semptom_cevirisi.values())

for semptom in tum_semptomlar_listesi:
    df_ml[semptom] = df_ml[semptom_kolonlari].apply(
        lambda row: 1 if semptom in row.values else 0, axis=1
    )

df_ml = df_ml.drop(columns=semptom_kolonlari)

print(f"Yeni shape: {df_ml.shape}")
print(f"Kolonlar: Disease + {df_ml.shape[1]-1} semptom kolonu")

X = df_ml.drop(columns=['Disease'])
y = df_ml['Disease']

print(f"\n X shape: {X.shape}")
print(f" y shape: {y.shape}")
print(f" Sınıf sayısı: {y.nunique()}")

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

from google.colab import drive
drive.mount('/content/drive')

df_turkce = pd.read_csv('/content/drive/MyDrive/archive/dataset_turkce.csv')

print(f"Dataset yüklendi: {df_turkce.shape}")
print(df_turkce.head(3))

semptom_cevirisi = {
    'abdominal_pain': 'karın ağrısı',
    'abnormal_menstruation': 'anormal adet düzensizliği',
    'acidity': 'mide asidi',
    'acute_liver_failure': 'akut karaciğer yetmezliği',
    'altered_sensorium': 'bilinç değişikliği',
    'anxiety': 'anksiyete',
    'back_pain': 'sırt ağrısı',
    'belly_pain': 'göbek ağrısı',
    'blackheads': 'siyah nokta',
    'bladder_discomfort': 'mesane rahatsızlığı',
    'blister': 'su kabarcığı',
    'blood_in_sputum': 'balgamda kan',
    'bloody_stool': 'kanlı dışkı',
    'blurred_and_distorted_vision': 'bulanık ve bozuk görme',
    'breathlessness': 'nefes darlığı',
    'brittle_nails': 'kırılgan tırnaklar',
    'bruising': 'morarma',
    'burning_micturition': 'yanma ile idrara çıkma',
    'chest_pain': 'göğüs ağrısı',
    'chills': 'üşüme',
    'cold_hands_and_feets': 'soğuk eller ve ayaklar',
    'coma': 'koma',
    'congestion': 'burun tıkanıklığı',
    'constipation': 'kabızlık',
    'continuous_feel_of_urine': 'sürekli idrara sıkışma hissi',
    'continuous_sneezing': 'sürekli hapşırma',
    'cough': 'öksürük',
    'cramps': 'kramp',
    'dark_urine': 'koyu renkli idrar',
    'dehydration': 'dehidrasyon',
    'depression': 'depresyon',
    'diarrhoea': 'ishal',
    'dischromic _patches': 'renk değişimi lekeleri',
    'distention_of_abdomen': 'karın şişkinliği',
    'dizziness': 'baş dönmesi',
    'drying_and_tingling_lips': 'dudak kuruması ve karıncalanma',
    'enlarged_thyroid': 'büyümüş tiroid',
    'excessive_hunger': 'aşırı açlık',
    'extra_marital_contacts': 'cinsel temas öyküsü',
    'family_history': 'aile hastalık geçmişi',
    'fast_heart_rate': 'hızlı kalp atışı',
    'fatigue': 'yorgunluk',
    'fluid_overload': 'sıvı aşırı yüklenmesi',
    'foul_smell_of urine': 'kötü kokulu idrar',
    'headache': 'baş ağrısı',
    'high_fever': 'yüksek ateş',
    'hip_joint_pain': 'kalça eklem ağrısı',
    'history_of_alcohol_consumption': 'alkol kullanım geçmişi',
    'increased_appetite': 'artan iştah',
    'indigestion': 'hazımsızlık',
    'inflammatory_nails': 'iltihaplanmış tırnaklar',
    'internal_itching': 'iç kaşıntı',
    'irregular_sugar_level': 'düzensiz kan şekeri',
    'irritability': 'sinirlilik',
    'irritation_in_anus': 'anüs tahrişi',
    'itching': 'kaşıntı',
    'joint_pain': 'eklem ağrısı',
    'knee_pain': 'diz ağrısı',
    'lack_of_concentration': 'konsantrasyon güçlüğü',
    'lethargy': 'halsizlik',
    'loss_of_appetite': 'iştah kaybı',
    'loss_of_balance': 'denge kaybı',
    'loss_of_smell': 'koku kaybı',
    'malaise': 'genel vücut yorgunluğu',
    'mild_fever': 'hafif ateş',
    'mood_swings': 'ruh hali dalgalanmaları',
    'movement_stiffness': 'hareket tutukluğu',
    'mucoid_sputum': 'mukuslu balgam',
    'muscle_pain': 'kas ağrısı',
    'muscle_wasting': 'kas erimesi',
    'muscle_weakness': 'kas güçsüzlüğü',
    'nausea': 'bulantı',
    'neck_pain': 'boyun ağrısı',
    'nodal_skin_eruptions': 'nodüler cilt döküntüsü',
    'obesity': 'obezite',
    'pain_behind_the_eyes': 'göz arkası ağrısı',
    'pain_during_bowel_movements': 'dışkılama sırasında ağrı',
    'pain_in_anal_region': 'anüs bölgesinde ağrı',
    'painful_walking': 'ağrılı yürüyüş',
    'palpitations': 'çarpıntı',
    'passage_of_gases': 'gaz çıkarma',
    'patches_in_throat': 'boğazda leke',
    'phlegm': 'balgam',
    'polyuria': 'sık idrara çıkma',
    'prominent_veins_on_calf': 'baldırda belirgin damarlar',
    'puffy_face_and_eyes': 'şişmiş yüz ve gözler',
    'pus_filled_pimples': 'irin dolu sivilce',
    'receiving_blood_transfusion': 'kan transfüzyonu alma',
    'receiving_unsterile_injections': 'steril olmayan enjeksiyon',
    'red_sore_around_nose': 'burun çevresinde kızarıklık',
    'red_spots_over_body': 'vücutta kırmızı lekeler',
    'redness_of_eyes': 'göz kızarıklığı',
    'restlessness': 'huzursuzluk',
    'runny_nose': 'burun akıntısı',
    'rusty_sputum': 'paslı renkli balgam',
    'scurring': 'kabuk oluşumu',
    'shivering': 'titreme',
    'silver_like_dusting': 'gümüş rengi pullanma',
    'sinus_pressure': 'sinüs basıncı',
    'skin_peeling': 'cilt soyulması',
    'skin_rash': 'cilt döküntüsü',
    'slurred_speech': 'peltek konuşma',
    'small_dents_in_nails': 'tırnaklarda çukurlaşma',
    'spinning_movements': 'dönme hissi',
    'spotting_ urination': 'lekeli idrara çıkma',
    'stiff_neck': 'boyun tutulması',
    'stomach_bleeding': 'mide kanaması',
    'stomach_pain': 'mide ağrısı',
    'sunken_eyes': 'çökmüş gözler',
    'sweating': 'terleme',
    'swelled_lymph_nodes': 'şişmiş lenf düğümleri',
    'swelling_joints': 'eklem şişmesi',
    'swelling_of_stomach': 'mide şişmesi',
    'swollen_blood_vessels': 'şişmiş kan damarları',
    'swollen_extremeties': 'şişmiş ekstremiteler',
    'swollen_legs': 'şişmiş bacaklar',
    'throat_irritation': 'boğaz tahrişi',
    'toxic_look_(typhos)': 'toksik görünüm',
    'ulcers_on_tongue': 'dil ülseri',
    'unsteadiness': 'dengesizlik',
    'visual_disturbances': 'görsel bozukluklar',
    'vomiting': 'kusma',
    'watering_from_eyes': 'gözden su akması',
    'weakness_in_limbs': 'uzuvlarda güçsüzlük',
    'weakness_of_one_body_side': 'vücudun bir tarafında güçsüzlük',
    'weight_gain': 'kilo alımı',
    'weight_loss': 'kilo kaybı',
    'yellow_crust_ooze': 'sarı kabuk akıntısı',
    'yellow_urine': 'sarı idrar',
    'yellowing_of_eyes': 'gözlerin sararması',
    'yellowish_skin': 'sarı cilt',
}

df_ml = df_turkce.copy()
semptom_kolonlari = [f'Symptom_{i}' for i in range(1, 18)]
df_ml[semptom_kolonlari] = df_ml[semptom_kolonlari].fillna('')

tum_semptomlar_listesi = list(semptom_cevirisi.values())

for semptom in tum_semptomlar_listesi:
    df_ml[semptom] = df_ml[semptom_kolonlari].apply(
        lambda row: 1 if semptom in row.values else 0, axis=1
    )

df_ml = df_ml.drop(columns=semptom_kolonlari)

X = df_ml.drop(columns=['Disease'])
y = df_ml['Disease']

print(f"X shape: {X.shape}")
print(f"y shape: {y.shape}")
print(f"Sınıf sayısı: {y.nunique()}")
print(X.iloc[:3, :5])

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import pickle
import pandas as pd

X.to_csv('/content/drive/MyDrive/archive/X_onehot.csv', index=False)
y.to_csv('/content/drive/MyDrive/archive/y_labels.csv', index=False)
print(" X_onehot.csv kaydedildi")
print(" y_labels.csv kaydedildi")

import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

X = pd.read_csv('/content/drive/MyDrive/archive/X_onehot.csv')
y = pd.read_csv('/content/drive/MyDrive/archive/y_labels.csv').squeeze()

print(f"X shape: {X.shape}")
print(f"y shape: {y.shape}")

from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import pickle

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

nb_model = GaussianNB()
nb_model.fit(X_train, y_train)
y_pred = nb_model.predict(X_test)

acc  = accuracy_score(y_test, y_pred)
prec = precision_score(y_test, y_pred, average='weighted', zero_division=0)
rec  = recall_score(y_test, y_pred, average='weighted', zero_division=0)
f1   = f1_score(y_test, y_pred, average='weighted', zero_division=0)

print("Naive Bayes")
print(f"Accuracy:  {acc:.4f}")
print(f"Precision: {prec:.4f}")
print(f"Recall:    {rec:.4f}")
print(f"F1 Score:  {f1:.4f}")

with open('/content/drive/MyDrive/archive/naive_bayes_model.pkl', 'wb') as f:
    pickle.dump(nb_model, f)

print("naive_bayes_model.pkl kaydedildi")

print(f"Toplam satır: {len(X)}")
print(f"Tekrarsız satır: {len(X.drop_duplicates())}")
print(f"Tekrar eden satır sayısı: {len(X) - len(X.drop_duplicates())}")

import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

X = pd.read_csv('/content/drive/MyDrive/archive/X_onehot.csv')
y = pd.read_csv('/content/drive/MyDrive/archive/y_labels.csv').squeeze()

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import pickle

X_benzersiz = X.drop_duplicates()
print(f"{len(X_benzersiz)}")

benzersiz_indeksler = X_benzersiz.index.tolist()

train_indeks, test_indeks = train_test_split(
    benzersiz_indeksler, test_size=0.2, random_state=42
)

X_merged = X.copy()
X_merged['__key__'] = X_merged.apply(tuple, axis=1)

X_benzersiz_key = X.iloc[train_indeks].apply(tuple, axis=1).tolist()
train_mask = X_merged['__key__'].isin(X_benzersiz_key)

X_train = X[train_mask].drop(columns=[], errors='ignore')
y_train = y[train_mask]

X_test = X[~train_mask]
y_test = y[~train_mask]

X_train = X_train.copy()
X_test = X_test.copy()

print(f"Eğitim seti: {X_train.shape}")
print(f"Test seti:   {X_test.shape}")
print(f"Test setinde eğitimde görülen satır: {X_test.apply(tuple, axis=1).isin(X_train.apply(tuple, axis=1)).any()}")

nb_model = GaussianNB()
nb_model.fit(X_train, y_train)
y_pred = nb_model.predict(X_test)

acc  = accuracy_score(y_test, y_pred)
prec = precision_score(y_test, y_pred, average='weighted', zero_division=0)
rec  = recall_score(y_test, y_pred, average='weighted', zero_division=0)
f1   = f1_score(y_test, y_pred, average='weighted', zero_division=0)

print("\nNaive Bayes")
print(f"Accuracy:  {acc:.4f}")
print(f"Precision: {prec:.4f}")
print(f"Recall:    {rec:.4f}")
print(f"F1 Score:  {f1:.4f}")

with open('/content/drive/MyDrive/archive/naive_bayes_model.pkl', 'wb') as f:
    pickle.dump(nb_model, f)
print("\n naive_bayes_model.pkl kaydedildi")

import pandas as pd
import matplotlib.pyplot as plt

onem_skorlari = rf_model.feature_importances_
belirti_isimleri = X.columns.tolist()

df_onem = pd.DataFrame({
    'Belirti': belirti_isimleri,
    'Önem': onem_skorlari
}).sort_values('Önem', ascending=False)

print(" En önemli 20 belirti ")
print(df_onem.head(20).to_string(index=False))

print(f"\n=== Önem skoru 0 olan belirti sayısı: {(df_onem['Önem'] == 0).sum()} ===")
print(f"=== Önem skoru 0'dan büyük belirti sayısı: {(df_onem['Önem'] > 0).sum()} ===")

esik = 0.005
secilen = df_onem[df_onem['Önem'] > esik]
print(f"Eşik {esik} üstündeki belirti sayısı: {len(secilen)}")

esik = 0.008
secilen = df_onem[df_onem['Önem'] > esik]
print(f"Eşik {esik} üstündeki belirti sayısı: {len(secilen)}")

esik = 0.010
secilen = df_onem[df_onem['Önem'] > esik]
print(f"Eşik {esik} üstündeki belirti sayısı: {len(secilen)}")

from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import pickle

secilen_belirtiler = df_onem[df_onem['Önem'] > 0.005]['Belirti'].tolist()
print(f"Seçilen belirti sayısı: {len(secilen_belirtiler)}")

X_secilen = X[secilen_belirtiler]

X_benzersiz = X_secilen.drop_duplicates()
benzersiz_indeksler = X_benzersiz.index.tolist()

train_indeks, test_indeks = train_test_split(
    benzersiz_indeksler, test_size=0.2, random_state=42
)

X_merged = X_secilen.copy()
X_merged['__key__'] = X_merged.apply(tuple, axis=1)
X_benzersiz_key = X_secilen.iloc[train_indeks].apply(tuple, axis=1).tolist()
train_mask = X_merged['__key__'].isin(X_benzersiz_key)

X_train = X_secilen[train_mask]
y_train = y[train_mask]
X_test = X_secilen[~train_mask]
y_test = y[~train_mask]

print(f"Eğitim seti: {X_train.shape}")
print(f"Test seti:   {X_test.shape}")

modeller = {
    'Decision Tree': DecisionTreeClassifier(random_state=42),
}

sonuclar = []

for model_adi, model in modeller.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    acc  = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred, average='weighted', zero_division=0)
    rec  = recall_score(y_test, y_pred, average='weighted', zero_division=0)
    f1   = f1_score(y_test, y_pred, average='weighted', zero_division=0)

    sonuclar.append({
        'Model': model_adi,
        'Accuracy': f"{acc:.4f}",
        'Precision': f"{prec:.4f}",
        'Recall': f"{rec:.4f}",
        'F1 Score': f"{f1:.4f}"
    })

    print(f"\n=== {model_adi} ===")
    print(f"Accuracy:  {acc:.4f}")
    print(f"Precision: {prec:.4f}")
    print(f"Recall:    {rec:.4f}")
    print(f"F1 Score:  {f1:.4f}")

    dosya_adi = model_adi.replace(' ', '_').lower()
    with open(f'/content/drive/MyDrive/archive/{dosya_adi}_model.pkl', 'wb') as f:
        pickle.dump(model, f)
    print(f" {dosya_adi}_model.pkl kaydedildi")


df_sonuc = pd.DataFrame(sonuclar)
df_sonuc.to_csv('/content/drive/MyDrive/archive/model_sonuclari.csv', index=False)
print("\n Tüm modeller kaydedildi!")

from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import pickle

secilen_belirtiler = df_onem[df_onem['Önem'] > 0.005]['Belirti'].tolist()
print(f"Seçilen belirti sayısı: {len(secilen_belirtiler)}")

X_secilen = X[secilen_belirtiler]

X_benzersiz = X_secilen.drop_duplicates()
benzersiz_indeksler = X_benzersiz.index.tolist()

train_indeks, test_indeks = train_test_split(
    benzersiz_indeksler, test_size=0.2, random_state=42
)

X_merged = X_secilen.copy()
X_merged['__key__'] = X_merged.apply(tuple, axis=1)
X_benzersiz_key = X_secilen.iloc[train_indeks].apply(tuple, axis=1).tolist()
train_mask = X_merged['__key__'].isin(X_benzersiz_key)

X_train = X_secilen[train_mask]
y_train = y[train_mask]
X_test = X_secilen[~train_mask]
y_test = y[~train_mask]

print(f"Eğitim seti: {X_train.shape}")
print(f"Test seti:   {X_test.shape}")

modeller = {
    'Random Forest': RandomForestClassifier(n_estimators=100, random_state=42),
}

sonuclar = []

for model_adi, model in modeller.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    acc  = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred, average='weighted', zero_division=0)
    rec  = recall_score(y_test, y_pred, average='weighted', zero_division=0)
    f1   = f1_score(y_test, y_pred, average='weighted', zero_division=0)

    sonuclar.append({
        'Model': model_adi,
        'Accuracy': f"{acc:.4f}",
        'Precision': f"{prec:.4f}",
        'Recall': f"{rec:.4f}",
        'F1 Score': f"{f1:.4f}"
    })

    print(f"\n=== {model_adi} ===")
    print(f"Accuracy:  {acc:.4f}")
    print(f"Precision: {prec:.4f}")
    print(f"Recall:    {rec:.4f}")
    print(f"F1 Score:  {f1:.4f}")

    dosya_adi = model_adi.replace(' ', '_').lower()
    with open(f'/content/drive/MyDrive/archive/{dosya_adi}_model.pkl', 'wb') as f:
        pickle.dump(model, f)
    print(f" {dosya_adi}_model.pkl kaydedildi")


df_sonuc = pd.DataFrame(sonuclar)
df_sonuc.to_csv('/content/drive/MyDrive/archive/model_sonuclari.csv', index=False)
print("\n Tüm modeller kaydedildi!")

from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import pickle

secilen_belirtiler = df_onem[df_onem['Önem'] > 0.005]['Belirti'].tolist()
print(f"Seçilen belirti sayısı: {len(secilen_belirtiler)}")

X_secilen = X[secilen_belirtiler]

X_benzersiz = X_secilen.drop_duplicates()
benzersiz_indeksler = X_benzersiz.index.tolist()

train_indeks, test_indeks = train_test_split(
    benzersiz_indeksler, test_size=0.2, random_state=42
)

X_merged = X_secilen.copy()
X_merged['__key__'] = X_merged.apply(tuple, axis=1)
X_benzersiz_key = X_secilen.iloc[train_indeks].apply(tuple, axis=1).tolist()
train_mask = X_merged['__key__'].isin(X_benzersiz_key)

X_train = X_secilen[train_mask]
y_train = y[train_mask]
X_test = X_secilen[~train_mask]
y_test = y[~train_mask]

print(f"Eğitim seti: {X_train.shape}")
print(f"Test seti:   {X_test.shape}")

modeller = {
    'Naive Bayes': GaussianNB(),
}

sonuclar = []

for model_adi, model in modeller.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    acc  = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred, average='weighted', zero_division=0)
    rec  = recall_score(y_test, y_pred, average='weighted', zero_division=0)
    f1   = f1_score(y_test, y_pred, average='weighted', zero_division=0)

    sonuclar.append({
        'Model': model_adi,
        'Accuracy': f"{acc:.4f}",
        'Precision': f"{prec:.4f}",
        'Recall': f"{rec:.4f}",
        'F1 Score': f"{f1:.4f}"
    })

    print(f"\n=== {model_adi} ===")
    print(f"Accuracy:  {acc:.4f}")
    print(f"Precision: {prec:.4f}")
    print(f"Recall:    {rec:.4f}")
    print(f"F1 Score:  {f1:.4f}")

    dosya_adi = model_adi.replace(' ', '_').lower()
    with open(f'/content/drive/MyDrive/archive/{dosya_adi}_model.pkl', 'wb') as f:
        pickle.dump(model, f)
    print(f" {dosya_adi}_model.pkl kaydedildi")


df_sonuc = pd.DataFrame(sonuclar)
df_sonuc.to_csv('/content/drive/MyDrive/archive/model_sonuclari.csv', index=False)
print("\n Tüm modeller kaydedildi!")

import pandas as pd
from google.colab import drive
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
drive.mount('/content/drive')

X = pd.read_csv('/content/drive/MyDrive/archive/X_onehot.csv')
y = pd.read_csv('/content/drive/MyDrive/archive/y_labels.csv').squeeze()

rf_temp = RandomForestClassifier(n_estimators=100, random_state=42)
rf_temp.fit(X, y)

df_onem = pd.DataFrame({
    'Belirti': X.columns.tolist(),
    'Önem': rf_temp.feature_importances_
}).sort_values('Önem', ascending=False)

secilen_belirtiler = df_onem[df_onem['Önem'] > 0.005]['Belirti'].tolist()
X_secilen = X[secilen_belirtiler]
print(f"Seçilen belirti sayısı: {len(secilen_belirtiler)}")

X_benzersiz = X_secilen.drop_duplicates()
benzersiz_indeksler = X_benzersiz.index.tolist()
train_indeks, test_indeks = train_test_split(
    benzersiz_indeksler, test_size=0.2, random_state=42
)
X_merged = X_secilen.copy()
X_merged['__key__'] = X_merged.apply(tuple, axis=1)
X_benzersiz_key = X_secilen.iloc[train_indeks].apply(tuple, axis=1).tolist()
train_mask = X_merged['__key__'].isin(X_benzersiz_key)

X_train = X_secilen[train_mask]
y_train = y[train_mask]
X_test = X_secilen[~train_mask]
y_test = y[~train_mask]

print(f" Hazır! X_train: {X_train.shape}, X_test: {X_test.shape}")

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import pickle

svm_model = SVC(kernel='rbf', random_state=42)
svm_model.fit(X_train, y_train)
y_pred_svm = svm_model.predict(X_test)

acc  = accuracy_score(y_test, y_pred_svm)
prec = precision_score(y_test, y_pred_svm, average='weighted', zero_division=0)
rec  = recall_score(y_test, y_pred_svm, average='weighted', zero_division=0)
f1   = f1_score(y_test, y_pred_svm, average='weighted', zero_division=0)

print(f"Accuracy:  {acc:.4f}")
print(f"Precision: {prec:.4f}")
print(f"Recall:    {rec:.4f}")
print(f"F1 Score:  {f1:.4f}")

with open('/content/drive/MyDrive/archive/svm_model.pkl', 'wb') as f:
    pickle.dump(svm_model, f)
print("svm_model.pkl kaydedildi")

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import pickle

secilen_belirtiler_58 = df_onem[df_onem['Önem'] > 0.008]['Belirti'].tolist()
print(f"Seçilen belirti sayısı: {len(secilen_belirtiler_58)}")

X_secilen_58 = X[secilen_belirtiler_58]

X_benzersiz_58 = X_secilen_58.drop_duplicates()
benzersiz_indeksler_58 = X_benzersiz_58.index.tolist()
train_indeks_58, test_indeks_58 = train_test_split(
    benzersiz_indeksler_58, test_size=0.2, random_state=42
)
X_merged_58 = X_secilen_58.copy()
X_merged_58['__key__'] = X_merged_58.apply(tuple, axis=1)
X_benzersiz_key_58 = X_secilen_58.iloc[train_indeks_58].apply(tuple, axis=1).tolist()
train_mask_58 = X_merged_58['__key__'].isin(X_benzersiz_key_58)

X_train_58 = X_secilen_58[train_mask_58]
y_train_58 = y[train_mask_58]
X_test_58 = X_secilen_58[~train_mask_58]
y_test_58 = y[~train_mask_58]

print(f"Eğitim seti: {X_train_58.shape}")
print(f"Test seti:   {X_test_58.shape}")

svm_model = SVC(kernel='rbf', random_state=42)
svm_model.fit(X_train_58, y_train_58)
y_pred_svm = svm_model.predict(X_test_58)

acc  = accuracy_score(y_test_58, y_pred_svm)
prec = precision_score(y_test_58, y_pred_svm, average='weighted', zero_division=0)
rec  = recall_score(y_test_58, y_pred_svm, average='weighted', zero_division=0)
f1   = f1_score(y_test_58, y_pred_svm, average='weighted', zero_division=0)

print(f"Accuracy:  {acc:.4f}")
print(f"Precision: {prec:.4f}")
print(f"Recall:    {rec:.4f}")
print(f"F1 Score:  {f1:.4f}")

with open('/content/drive/MyDrive/archive/svm_model.pkl', 'wb') as f:
    pickle.dump(svm_model, f)
print(" svm_model.pkl kaydedildi")

esik = 0.006
secilen = df_onem[df_onem['Önem'] > esik]
print(f"Eşik {esik} üstündeki belirti sayısı: {len(secilen)}")

esik = 0.007
secilen = df_onem[df_onem['Önem'] > esik]
print(f"Eşik {esik} üstündeki belirti sayısı: {len(secilen)}")

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import pickle

secilen_belirtiler_81 = df_onem[df_onem['Önem'] > 0.006]['Belirti'].tolist()
print(f"Seçilen belirti sayısı: {len(secilen_belirtiler_81)}")

X_secilen_81 = X[secilen_belirtiler_81]


X_benzersiz_81 = X_secilen_81.drop_duplicates()
benzersiz_indeksler_81 = X_benzersiz_81.index.tolist()
train_indeks_81, test_indeks_81 = train_test_split(
    benzersiz_indeksler_81, test_size=0.2, random_state=42
)
X_merged_81 = X_secilen_81.copy()
X_merged_81['__key__'] = X_merged_81.apply(tuple, axis=1)
X_benzersiz_key_81 = X_secilen_81.iloc[train_indeks_81].apply(tuple, axis=1).tolist()
train_mask_81 = X_merged_81['__key__'].isin(X_benzersiz_key_81)

X_train_81 = X_secilen_81[train_mask_81]
y_train_81 = y[train_mask_81]
X_test_81 = X_secilen_81[~train_mask_81]
y_test_81 = y[~train_mask_81]

print(f"Eğitim seti: {X_train_81.shape}")
print(f"Test seti:   {X_test_81.shape}")


svm_model = SVC(kernel='rbf', random_state=42)
svm_model.fit(X_train_81, y_train_81)
y_pred_svm = svm_model.predict(X_test_81)

acc  = accuracy_score(y_test_81, y_pred_svm)
prec = precision_score(y_test_81, y_pred_svm, average='weighted', zero_division=0)
rec  = recall_score(y_test_81, y_pred_svm, average='weighted', zero_division=0)
f1   = f1_score(y_test_81, y_pred_svm, average='weighted', zero_division=0)


print(f"Accuracy:  {acc:.4f}")
print(f"Precision: {prec:.4f}")
print(f"Recall:    {rec:.4f}")
print(f"F1 Score:  {f1:.4f}")

with open('/content/drive/MyDrive/archive/svm_model.pkl', 'wb') as f:
    pickle.dump(svm_model, f)
print("svm_model.pkl kaydedildi")

from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import pickle

mlp_model = MLPClassifier(
    hidden_layer_sizes=(100, 50),
    max_iter=500,
    random_state=42
)

mlp_model.fit(X_train, y_train)
y_pred_mlp = mlp_model.predict(X_test)

acc  = accuracy_score(y_test, y_pred_mlp)
prec = precision_score(y_test, y_pred_mlp, average='weighted', zero_division=0)
rec  = recall_score(y_test, y_pred_mlp, average='weighted', zero_division=0)
f1   = f1_score(y_test, y_pred_mlp, average='weighted', zero_division=0)

print(f"Accuracy:  {acc:.4f}")
print(f"Precision: {prec:.4f}")
print(f"Recall:    {rec:.4f}")
print(f"F1 Score:  {f1:.4f}")

with open('/content/drive/MyDrive/archive/mlp_model.pkl', 'wb') as f:
    pickle.dump(mlp_model, f)
print(" mlp_model.pkl kaydedildi")

from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import pickle


secilen_belirtiler_81 = df_onem[df_onem['Önem'] > 0.006]['Belirti'].tolist()
X_secilen_81 = X[secilen_belirtiler_81]

X_benzersiz_81 = X_secilen_81.drop_duplicates()
benzersiz_indeksler_81 = X_benzersiz_81.index.tolist()
train_indeks_81, test_indeks_81 = train_test_split(
    benzersiz_indeksler_81, test_size=0.2, random_state=42
)
X_merged_81 = X_secilen_81.copy()
X_merged_81['__key__'] = X_merged_81.apply(tuple, axis=1)
X_benzersiz_key_81 = X_secilen_81.iloc[train_indeks_81].apply(tuple, axis=1).tolist()
train_mask_81 = X_merged_81['__key__'].isin(X_benzersiz_key_81)

X_train_81 = X_secilen_81[train_mask_81]
y_train_81 = y[train_mask_81]
X_test_81 = X_secilen_81[~train_mask_81]
y_test_81 = y[~train_mask_81]

mlp_model = MLPClassifier(
    hidden_layer_sizes=(100, 50),
    max_iter=500,
    random_state=42
)

mlp_model.fit(X_train_81, y_train_81)
y_pred_mlp = mlp_model.predict(X_test_81)

acc  = accuracy_score(y_test_81, y_pred_mlp)
prec = precision_score(y_test_81, y_pred_mlp, average='weighted', zero_division=0)
rec  = recall_score(y_test_81, y_pred_mlp, average='weighted', zero_division=0)
f1   = f1_score(y_test_81, y_pred_mlp, average='weighted', zero_division=0)


print(f"Accuracy:  {acc:.4f}")
print(f"Precision: {prec:.4f}")
print(f"Recall:    {rec:.4f}")
print(f"F1 Score:  {f1:.4f}")

with open('/content/drive/MyDrive/archive/mlp_model.pkl', 'wb') as f:
    pickle.dump(mlp_model, f)
print("mlp_model.pkl kaydedildi")